### ISSUE TITLE
Typo in Welstandsnota XSD definitie element

### ISSUE THREAD

**Issue by justb4** [Geonovum/imwe2014#1]
In IMWE2014 XSD v1.0RC1 zit een typo: "begenzing" ipv "begrenzing", zie onder.

    <complexType name="WelstandsnotaType">
        <complexContent>
            <extension base="imwe:PlangebiedType">
                <sequence>
                    <element name="typePlan" type="imwe:RuimtelijkPlanOfBesluit_WNType"/>
                    <element name="beleidsmatigVerantwoordelijkeOverheid" type="imwe:Overheden_GType"/>
                    <element name="naamOverheid" type="imwe:NotEmptyString"/>
                    <element name="naam" type="imwe:NotEmptyString"/>
                    <element name="locatieNaam" type="imwe:NotEmptyString" minOccurs="0" maxOccurs="unbounded"/>
                    <element name="planstatusInfo" type="imwe:PlanstatusEnDatumPropertyType"/>
                    <element name="besluitnummer" type="imwe:NotEmptyString" minOccurs="0"/>
                    <element name="verwijzingNaarVaststellingsbesluit" type="imwe:NotEmptyString" minOccurs="0"/>
                    <element name="verwijzingNaarTekstInfo" type="imwe:TekstReferentieWN_WNPropertyType" maxOccurs="2"/>
                    <element name="ondergrondInfo" type="imwe:OndergrondReferentiePropertyType" maxOccurs="unbounded"/>
                    <element name="verwijzingNaarIllustratieInfo" type="imwe:IllustratiereferentiePropertyType"
                             minOccurs="0" maxOccurs="unbounded"/>
                    <element name="verwijzingNaarExternPlanInfo" type="imwe:ExternPlanReferentieWN_WNPropertyType"
                             minOccurs="0" maxOccurs="unbounded"/>
                    <element name="verwijzingNorm" type="imwe:NotEmptyString"/>
                    <element name="beginTijd" type="date"/>
                    <element name="eindTijd" type="date" minOccurs="0"/>
                    ===> <element name="begenzing" type="imwe:GeometrieWNgebiedPropertyType"/> <===
                </sequence>
            </extension>
        </complexContent>
    </complexType>

**Comment by PalmJanssen** [comment]
Aangepast in versie RC3:
Welstandsnota begenzing -> begrenzing.

**Comment by justb4** [comment]
Ok!
