### ISSUE TITLE
Hoe moeten IMWEPT2014 tekst/illustratie objecten eruit komen te zien?

### ISSUE THREAD

**Issue by justb4** [Geonovum/imwe2014#3]
In IMWE2014 wordt binnen de 4 hoofdobjectypen verwezen naar Text en Illustraties. Deze laatsten staan gemodelleerd in IMWEPT2014 en gebaseerd op IMROPT2012. Bij het maken van proefbestanden zijn volgens mij de verwijzingen als volgt, zie voorbeeldbestand: https://github.com/Geonovum/imwe2014/blob/master/samples/imwe2014/FC-IMWE2014-1.xml

            <imwe:verwijzingNaarTekstInfo>
                
                <imwe:TekstReferentieNG_WN>
                     <imwe:verwijzingNaarTekst>pt_NL.IMWE.1709.WelstandsNiveauGebied.23</imwe:verwijzingNaarTekst>
                    <imwe:typeTekst>beschrijving</imwe:typeTekst>
                </imwe:TekstReferentieNG_WN>
            </imwe:verwijzingNaarTekstInfo>

Dus een verwijzing zoals 'pt_' + planID bijv 'pt_NL.IMWE.1709.WelstandsNiveauGebied.23'. (?). In IMROPT2012 wordt direct verwezen naar een .pdf .html o.i.d., in ieder geval een "echt" bestand.

In IMWEPT2014 lijkt het erop dat teksten in een "imwept:FeatureCollectionIMWEPT" vervat zijn, waarbij iedere tekst (of onderdeel?) een "imwept:TekstObject" van type "imwept:TekstObjectType" is als volgt:

	<element name="TekstObject" type="imwept:TekstObjectType"/>
	<complexType name="TekstObjectType">
		<sequence>
			<element name="identificatie" type="string"/>
			<element name="verwijzingNaarPlangebied" type="string"/>
			<element name="volgnummer" type="integer"/>
			<element name="niveau" type="integer"/>
			<element name="type" type="imwept:Tekstobjecttype_WNType"/>
			<element name="titel" type="imwept:TitelInfoPropertyType"/>
			<element name="externeVerwijzing" type="string" minOccurs="0" maxOccurs="unbounded"/>
			<element name="tekst" type="string" minOccurs="0"/>
			<element name="tekstMetadata" type="imwept:TekstMetadataPropertyType" minOccurs="0"/>
			<element name="ouderID" type="imwept:TekstObjectPropertyType"/>
			<element name="interneVerwijzing" type="imwept:TekstObjectPropertyType" minOccurs="0"/>
		</sequence>
	</complexType>

De vragen hier zijn:

- klopt de aanname voor de tekst verwijzing vanuit de 4 W*-type objecten?
- waar zit nu de uiteindelijke tekst, i.e. de XHTML elementen? In het attribuut "tekst"?
- idem voor illustraties bijv 'i_NL.IMWE.1709.WelstandsNiveauGebied.23'

**Comment by PalmJanssen** [comment]
In IMWEPT2014 versie 1.0.0RC2:
identificatie is van type ID gemaakt.
<attribute name="identificatie" type="ID" use="required"/>

**Comment by justb4** [comment]
Nee (als dat enige wijziging is), want dan kun je nog steeds niet verwijzen. `identificatie` moet een `attribute` zijn, analoog aan IMROPT: 

        <attribute name="identificatie" type="ID" use="required"/>

**Comment by PalmJanssen** [comment]
Dank je. het is precies zo gedaan als je zegt

**Comment by justb4** [comment]
ok!
