### ISSUE TITLE
IMWE2014 XSD : Overheden_GType mist "gemeente" enumeratie

### ISSUE THREAD

**Issue by justb4** [Geonovum/imwe2014#4]
Volgens het "Informatiemodel Welstandsnota’s 2014 versie 1.0" kan een overheden GType twee mogelijke waarden hebben: 

          Definitie: Status: Stereotypes:
          Administratieve overheid. Approved
         «enumeration»
         Waarde: gemeentelijke overheid
         Waarde: deelgemeente/stadsdeel

Echter in de XSD IMWE2014-1.0.0RC1 is deze enumeratie als volgt:

	<simpleType name="Overheden_GType">
		<restriction base="string">
			<enumeration value="deelgemeente/stadsdeel"/>
		</restriction>
	</simpleType>

M.a.w. "gemeentelijke overheid" ontbreekt.

**Comment by PalmJanssen** [comment]
Opgelost in RC3:
overheden_G: toegevoegd gemeentelijke overheid (issue 4)

**Comment by justb4** [comment]
Top!

**Comment by PalmJanssen** [comment]
Kan je hier zo maar via email op antwoorden?

Van: Just van den Broecke [mailto:notifications@github.com]
Verzonden: donderdag 15 januari 2015 15:57
Aan: Geonovum/imwe2014
CC: Paul Janssen
Onderwerp: Re: [imwe2014] IMWE2014 XSD : Overheden_GType mist "gemeente" enumeratie (#4)


Top!

**Comment by justb4** [comment]
Ja via email of via web op GitHub. Voordeel van email is dat je ook de 
originele tekst "inlined" gaat zien, zoals hieronder.
