### ISSUE TITLE
XSD IMWE2014-1.0.0RC1 : slechts 1 waarde in enumeratie PlanstatusType

### ISSUE THREAD

**Issue by justb4** [Geonovum/imwe2014#5]
Uit PREWE2014: "Het domein Planstatus geeft de toegestane waarden voor het attribuut planstatus waaruit er één moet worden gekozen. De waarde van dit attribuut geeft de planstatus weer." PlanstatusType in de XSD IMWE2014-1.0.0RC1  kent slechts 1 enumeratie-waarde:

	<simpleType name="PlanstatusType">
		<restriction base="string">
			<enumeration value="geconsolideerd"/>
		</restriction>
	</simpleType>

Klopt dit??

**Comment by PalmJanssen** [comment]
opgelost in RC3
PlanstatusType: concept, voorontwerp, ontwerp, vastgesteld toegevoegd aan de reeds bestaande waarde geconsolideerd.

**Comment by justb4** [comment]
Prima: over en sluiten.
